---
server_privkey: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31303563633633643336313665623430313339363036363963383538336238376666346434316239
          6231613539383836316332363034653134616130623164320a633239393332616231343331623238
          61616364346631653964613136373137386437373234653539373530316635616339343364343230
          3166613035383462380a303962633064633337373534353330393465336531383437393566353563
          38316663316665323262363739643236313438363230323864663038316133633839366565333264
          3862376331626637333836336232323431656562616661316364
server_pubkey: vVAZQAH7Zv0igbAAJEwGBOY2T8X2Zrwve8j0ThSh7yw=
